# Generated by Django 2.2.28 on 2025-02-26 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250225_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 2, 26, 15, 26, 0, 754369), verbose_name='Дата комментария'),
        ),
    ]
